controller_list:
  - name: fake_right_arm_controller
    joints:
      - right/shoulder_yaw
      - right/shoulder_roll
      - right/shoulder_pitch
      - right/upperarm_roll
      - right/elbow
      - right/forearm_roll
      - right/wrist_pitch
  - name: fake_right_gripper_controller
    joints:
      - gripper
  - name: fake_left_arm_controller
    joints:
      - left/shoulder_yaw
      - left/shoulder_roll
      - left/shoulder_pitch
      - left/upperarm_roll
      - left/elbow
      - left/forearm_roll
      - left/wrist_pitch
  - name: fake_left_gripper_controller
    joints:
      - left/gripper
